# Generated by Django 2.2.7 on 2020-10-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='MovieType',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='MovieType',
        ),
    ]
